-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgmnTkV84/AY17ptSe
TrGdzAVnjZrRRjGy27GaR0Z79++gCgYIKoZIzj0DAQehRANCAASvEFfw96Q/nQdI
5LaCfBG+UGsVBuS0cQw5y2iOL3OJNVDFl3/zxE0damLKKIIbr+p7JFOCFjygAaWj
NEmgSfni
-----END PRIVATE KEY-----